package gatech.water_app.model;
import android.location.Location;


import java.util.Date;

/**
 * Created by vy on 2/24/17.
 */

public class WaterSourceReport extends Report {

    //Not sure if dataTime should be an int


    private WaterType type;
    private WaterCondition condition;
    private static int next_Id = 1;

//    Water source report
//    A user can submit this report any time they are logged in. This report consists of:
//
//    Date and time of report (can be autogenerated by application)+
//    Report Number (must be autogenerated by application)+
//    Name of reporter (can be autogenerated from user information)+
//    Location of water (manually entered. using any kind of location services or gps is extra credit)+
//    Type of water (Bottled, Well, Stream, Lake, Spring, Other)+
//    Condition of water (Waste, Treatable-Clear, Treatable-Muddy, Potable)+


    /**
     * Constructor
     * @param condition
     * @param type
     * @param reporter
     * @param reportNumber
     * @param dataTime
     */
    public WaterSourceReport(
            Date dataTime, String reportNumber, String reporter, WaterType type, WaterCondition condition, Location location) {
        super(dataTime,reportNumber,reporter, location);
        this.condition = condition;
        this.type = type;
    }

    /**
     * Constructor
     * @param reporter
     */
    public WaterSourceReport(String reporter) {
        this(new Date(), Integer.toString((int) next_Id++), reporter, null, null, null);
    }



    /**
     * Getter
     * @return
     */
    public Date getDataTime() {
        return super.getDataTime();
    }

    /**
     * Setter
     * @param dataTime
     */

    public void setDataTime(Date dataTime) {
        super.dataTime = dataTime;
    }

    /**
     * Getter
     * @return
     */
    public String getReportNumber() {
        return reportNumber;
    }

    /**
     * Setter
     * @param reportNumber
     */
    public void setReportNumber(String reportNumber) {
        this.reportNumber = reportNumber;
    }

    /**
     * Setter
     * @param reporter
     */
    public void setReporter(String reporter) {
        reporter = reporter;
    }

    /**
     * Getter
     * @return
     */
    public WaterType getType() {
        return type;
    }

    /**
     * Setter
     * @param type
     */
    public void setType(WaterType type) {
        this.type = type;
    }

    /**
     * Getter
     * @return
     */
    public WaterCondition getCondition() {
        return condition;
    }

    /**
     * Setter
     * @param condition
     */
    public void setCondition(WaterCondition condition) {
        this.condition = condition;
    }

    @Override
    public String toString() {
        return "WaterSourceReport{" +
                "dataTime=" + dataTime +
                ", reportNumber=" + reportNumber +
                ", Reporter='" + super.reporter + '\'' +
                ", type=" + type +
                ", condition=" + condition +
                '}';
    }


}
