package gatech.water_app.model;


import android.location.Location;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.Date;
/**
 * Created by Alex Thien An Le on 2/28/2017.
 * Modified by Khan Goksal on 3/2/2017
 */

public class WaterPurityReport extends Report {

    //Not sure if dataTime should be an in
    //Auto generated from existing Water Source(Report)
    private OverallCondition overallCondition;
    private double virusPPM;
    private double  contaminantPPM;
    private static int next_Id = 1;


//    Water Purity Report
//    A real water report would need to address multiple bacteria/virus and chemical contaminants. For our basic application, we assume that parts-per-million (PPM) is our measure and we will lump everything into two categories: Viruses and Contaminants.
//
//    Date and time of the report (can be autogenerated by application)+
//    Report Number (must be autogenerated by application)+
//    Name of Worker (can be autogenerated from worker information)+
//    Location of water (manually entered. using any kind of location services or gps is extra credit)+
//    Overall Condition (Safe / Treatable / Unsafe) --
//    Virus PPM--
//    Contaminant PPM--


    /**
     * Constructor
     * @param dataTime
     * @param reportNumber
     * @param Reporter
     * @param type
     * @param overallCondition
     * @param virusPPM
     * @param contaminantPPM
     */
    public WaterPurityReport(Date dataTime, String reportNumber, String Reporter, WaterType type, OverallCondition overallCondition, double virusPPM, double contaminantPPM, Location location) {
       super(dataTime, reportNumber, Reporter, location);
        this.overallCondition = overallCondition;
        this.virusPPM = virusPPM;
        this.contaminantPPM = contaminantPPM;
    }

    /**
     * Constructor
     * @param reporter
     */
    public WaterPurityReport(String reporter) {
        this(new Date(), Integer.toString(next_Id++), reporter, null, null, 0, 0, null);
    }

    /**
     * Getter
     * @return
     */
    public double getContaminantPPM() {
        return contaminantPPM;
    }

    /**
     * Setter
     * @param contaminantPPM
     */
    public void setContaminantPPM(double contaminantPPM) {
        this.contaminantPPM = contaminantPPM;
    }

    /**
     * Getter
     * @return
     */
    public double getVirusPPM() {
        return virusPPM;
    }

    /**
     * Setter
     * @param virusPPM
     */
    public void setVirusPPM(double virusPPM) {
        this.virusPPM = virusPPM;
    }

    /**
     * Getter
     * @return
     */
    public OverallCondition getOverallCondition() {
        return overallCondition;
    }

    /**
     * Setter
     * @param overallCondition
     */
    public void setOverallCondition(OverallCondition overallCondition) {
        this.overallCondition = overallCondition;
    }
    public JSONObject toJSONObject(){
        try {
            JSONObject data = new JSONObject();
            data.put("virus_ppm", this.virusPPM);
            data.put("contamination_ppm", this.contaminantPPM);
            data.put("overall_condition", this.overallCondition.toString());
            String dataString = data.toString();


            JSONObject returnJson = new JSONObject();
            returnJson.put("date", this.dataTime);
            returnJson.put("report_number", this.reportNumber);
            returnJson.put("reporter", this.reporter);
            returnJson.put("location", this.getLocation().toString());
            returnJson.put("data", dataString);
            return returnJson;
        } catch (JSONException E) {
            return null;
        }



    }

    //TODO : FINISH THIS
    @Override
    public String toString() {
        return "WaterSourceReport{" +
                "dataTime=" + dataTime +
                ", reportNumber=" + reportNumber +
                ", Reporter='" + super.reporter + '\'' +
                ", OverAll Condition=" + overallCondition +
                '}';
    }

}
